eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: 192.168.52.155
    port: 5672
    username: mytest
    password: mytest
##  sleuth:
##    sampler:
##      percentage: 1.0
##    enabled: false
  datasource:
    url: jdbc:mysql://192.168.52.155:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql