eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-miya
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: 192.168.52.155
    port: 5672
    username: mytest
    password: mytest
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: service-hi-zipkin